"use client";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Header from "./Chat/Header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider >
          <Header />
          {children}{" "}
        </SessionProvider>
      </body>
    </html>
  );
}
